version: "2"
services:

    php:
      container_name: php72
      restart: always
      build: ./build/php
      volumes:
        - ./apache.conf:/etc/apache2
        - ./app:/var/www/html
        - ./wp:/var/www/wp
      links:
        - mysql
      environment:
        - VIRTUAL_HOST_WEIGHT=1
        - VIRTUAL_HOST=*
      ports:
        - "80:80"
        

    mysql:
      restart: always
      image: mariadb
      container_name: mysql
      ports:
        - "3306:3306"
      volumes:
        - ./build/mysql/initdb:/docker-entrypoint-initdb.d
        - ./database:/var/lib/mysql
# 	          - ./build/mysql/sh:/build/mysql/sh #comment or remove this line when run on linux(native) os

      environment:
        - MYSQL_DATABASE=m4run
        - MYSQL_ROOT_PASSWORD=password_m4run
#      command: "/build/mysql/sh/permission.sh" #comment or remove this line when run on linux(native) os


    pma:
      container_name: sqladmin
      restart: always
      image: phpmyadmin/phpmyadmin
      links:
       - mysql:db
      ports:
        - 8080:80


  #  lb:
   #   container_name: haproxy
    #  restart: always
     # image: dockercloud/haproxy:1.3
  #    volumes:
   #     - /var/run/docker.sock:/var/run/docker.sock
    #  ports:
     ##   - 80:80
    #  links:
     #   - php


#    nginx:
#      container_name: nginx
#      restart: always
#      image: nginx
#      volumes:
#         - ./app/frontend/web:/usr/share/nginx/html
#         - ./app/backend/web:/usr/share/nginx/html/office
#      environment:
#        - VIRTUAL_HOST_WEIGHT=2
#        - VIRTUAL_HOST=*/assets/*, */office/assets/*


