version: "2"
services:


    php:
      container_name: apache-php72
      restart: always
      build: ./build/php
      volumes:
        - ./apache.conf:/etc/apache2
        - ./app:/var/www/html
        - ./wp:/var/www/wp
      links:
        - mysql
      environment:
        - VIRTUAL_HOST_WEIGHT=1
        - VIRTUAL_HOST=*
#      ports:
#        - "800:80"
        

    mysql:
      restart: always
      image: mariadb
      container_name: mysql
      ports:
        - "3306:3306"
      volumes:
        - ./build/mysql/initdb:/docker-entrypoint-initdb.d
        - ./database:/var/lib/mysql
# 	          - ./build/mysql/sh:/build/mysql/sh #comment or remove this line when run on linux(native) os

      environment:
        - MYSQL_DATABASE=m4run
        - MYSQL_ROOT_PASSWORD=password_m4run
#      command: "/build/mysql/sh/permission.sh" #comment or remove this line when run on linux(native) os


    pma:
      container_name: sqladmin
      restart: always
      image: phpmyadmin/phpmyadmin
      links:
       - mysql:db
      ports:
        - 8080:80


    nginx:
      container_name: nginx
      restart: always
      image: nginx
      volumes:
#        - ./nginx:/etc/nginx/
         - ./nginx:/etc/nginx/conf.d 
         - ./log:/var/log/nginx
      ports:
         - 80:80
